<a href="https://colab.research.google.com/github/ekramasif/Basic-Machine-Learning/blob/main/Recurrent%20Neural%20Network/Embedding_Sequence_LSTM_Keras_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
from tensorflow.keras import layers

embedding_layer = layers.Embedding(10, 5)

In [ ]:
result = embedding_layer(tf.constant([1, 2, 3]))
result.numpy()

array([[-0.01260991, -0.03372312,  0.00194007, -0.0095757 , -0.03261369],
       [-0.03920127, -0.03010396,  0.01364129, -0.00900034, -0.01983504],
       [-0.04036004,  0.00333557,  0.04447658, -0.02548711, -0.00562143]],
      dtype=float32)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

sentence = ['এই মাত্র পাওয়া সংবাদে জানা গেলো দেশ এর করোনা পরিস্থিতির উন্নতি হয়েছে', 
            'আমাদের সমাজে মুখোশধারী মানুষের অভাব নাই', 
            'আমরা দিন দিন বোকার রাজ্যে নির্বাসিত হচ্ছি']

tokenizer.fit_on_texts(sentence)

sequence = tokenizer.texts_to_sequences(sentence)

sequence

[[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 [14, 15, 16, 17, 18, 19],
 [20, 1, 1, 21, 22, 23, 24]]

In [ ]:
result = embedding_layer(tf.constant([1, 2, 3]))
result.numpy()

array([[-0.01260991, -0.03372312,  0.00194007, -0.0095757 , -0.03261369],
       [-0.03920127, -0.03010396,  0.01364129, -0.00900034, -0.01983504],
       [-0.04036004,  0.00333557,  0.04447658, -0.02548711, -0.00562143]],
      dtype=float32)

In [ ]:
from numpy import array
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Embedding, Dense, LSTM, Bidirectional

In [ ]:
# Real Life Example of Classification

train_ex = ['পণ্য ১০০% অরজিনাল কিন্তু আমার সাইজ যেটা আসছে ওটা আমাকে হচ্ছে না। আমার দরকার ৪২',
             'জুতা এপেক্সের ছিল একটু ভারী মনে হয়েছে জুতা এবং শক্ত। প্রোডাক্টটি ঠিক আছে যা চেয়েছিলাম তাই পেয়েছি  ওভারঅল ভালো',
             'আমি বিস্মিত, ঠিক যেমনটি চেয়েছিলাম তেমনটি পেয়েছি।। ধন্যবাদ এপেক্স ধন্যবাদ দারাজ।।',
             'অসাধারণ...ধন্যবাদ দারাজ।ধন্যবাদ এপেক্স। অরিজিনাল প্রোডাক্ট দেওয়ার জন্য।',
             'বেশি বলবনা এককথায় একশতে একশ। দাম অনুযায়ী খুবইসুন্দর প্রোডাক্ট, ধন্যবাদ দারাজ এবং সেলার ভাইটিকে।',
             'খুব একটা ভালো বলা চলে না। চাইলাম ৪১ আর দিলো ৪০।।ওনারা নিজেরাই ভালো রিভিউ দেয় কাস্টমারদের দেখানোর জন্ন্যে',
             'হাটার সময় অনেক আন ইজি পা বাকাতে প্রব্লেম হয়',
             'এপেক্স এর মত এই রকম প্রোডাক্ট আশা করা যায় না',
             'এপেক্স তো সবসময়ই ভালো বাট ডেলিভারি বাজে ছিলো😡😡😡 যেদিন দেয়ার কথা এর ২ দিন পর দিছে...',
             'ফালতু সেলার। মেসেজ দিয়া বল্লাম সাইজ যাতে উল্টোপাল্টা না আসে। কেউ অরডার করে প্রতারিত হবেন না।।'
             ]

# Reviews -- negative = 0 || positive = 1 (class/labels)
train_label = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])


In [ ]:
train_ex[4]

'বেশি বলবনা এককথায় একশতে একশ। দাম অনুযায়ী খুবইসুন্দর প্রোডাক্ট, ধন্যবাদ দারাজ এবং সেলার ভাইটিকে।'

In [ ]:
# tokenization and converting words into sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(train_ex)
dense_train_ex = tokenizer.texts_to_sequences(train_ex)

dense_train_ex

[[14, 15, 16, 17, 5, 6, 18, 19, 20, 21, 22, 7, 5, 23, 24],
 [8, 25, 26, 27, 28, 29, 30, 8, 9, 31, 32, 10, 33, 34, 11, 35, 36, 37, 1],
 [38, 39, 10, 40, 11, 41, 42, 2, 3, 2, 43],
 [44, 2, 45, 46, 47, 4, 48, 49],
 [50, 51, 52, 53, 54, 55, 56, 57, 4, 2, 58, 9, 59, 60],
 [61, 62, 1, 63, 64, 7, 65, 66, 67, 68, 69, 70, 1, 71, 72, 73, 74, 75],
 [76, 77, 78, 79, 80, 81, 82, 83, 84],
 [3, 12, 85, 86, 87, 4, 88, 89, 90, 13],
 [3, 91, 92, 1, 93, 94, 95, 96, 97, 98, 99, 12, 100, 101, 102, 103],
 [104, 105, 106, 107, 108, 6, 109, 110, 13, 111, 112, 113, 114, 115, 116, 117]]

In [ ]:
# def FindMaxLength(dense_train_ex):
#     maxList = max((x) for x in dense_train_ex)
#     maxLength = max(len(x) for x in dense_train_ex )
  
#     return maxList, maxLength
      
# # Driver Code
# print(FindMaxLength(dense_train_ex))

In [ ]:
# print(max(map(len, dense_train_ex)))

In [ ]:
def longest(dense_train_ex):
    longest_list = max(len(elem) for elem in dense_train_ex)
    return longest_list

print(longest(dense_train_ex))

19


In [ ]:
def largest(arr,n):
  
    # Initialize maximum element
    max = dense_train_ex[0]
  
    # Traverse array elements from second
    # and compare every element with 
    # current max
    for i in range(1, n):
        if dense_train_ex[i] > max:
            max = dense_train_ex[i]
    return max
  
# Driver Code
n = len(dense_train_ex)
Ans = largest(dense_train_ex,n)
print ("Largest in given array is",Ans)

Largest in given array is [104, 105, 106, 107, 108, 6, 109, 110, 13, 111, 112, 113, 114, 115, 116, 117]


In [ ]:
# padding the training documents in order to make them equal length
MAX_LENGTH = 19

padded_train_ex = pad_sequences(dense_train_ex, maxlen=MAX_LENGTH, padding='post')

for pd_sen in padded_train_ex:
  print(pd_sen)

[14 15 16 17  5  6 18 19 20 21 22  7  5 23 24  0  0  0  0]
[ 8 25 26 27 28 29 30  8  9 31 32 10 33 34 11 35 36 37  1]
[38 39 10 40 11 41 42  2  3  2 43  0  0  0  0  0  0  0  0]
[44  2 45 46 47  4 48 49  0  0  0  0  0  0  0  0  0  0  0]
[50 51 52 53 54 55 56 57  4  2 58  9 59 60  0  0  0  0  0]
[61 62  1 63 64  7 65 66 67 68 69 70  1 71 72 73 74 75  0]
[76 77 78 79 80 81 82 83 84  0  0  0  0  0  0  0  0  0  0]
[ 3 12 85 86 87  4 88 89 90 13  0  0  0  0  0  0  0  0  0]
[  3  91  92   1  93  94  95  96  97  98  99  12 100 101 102 103   0   0
   0]
[104 105 106 107 108   6 109 110  13 111 112 113 114 115 116 117   0   0
   0]


In [ ]:
def largest(arr,n):
  
    # Initialize maximum element
    max = Ans[0]
  
    # Traverse array elements from second
    # and compare every element with 
    # current max
    for i in range(1, n):
        if Ans[i] > max:
            max = Ans[i]
    return max
  
# Driver Code
n = len(Ans)
Ans1 = largest(Ans,n)
print ("VOCAB_SIZE:",Ans1)

VOCAB_SIZE: 117


In [ ]:
# Model Declaration
VOCAB_SIZE = 118

model = Sequential()

# Embedding Layer
embedding_layer = Embedding(input_dim=VOCAB_SIZE, output_dim=8, input_length=MAX_LENGTH)
model.add(embedding_layer)

# # Flatten Layer
# model.add(Flatten())

# model.add(Dense(units=160, activation='relu'))
# model.add(Dense(units=80, activation='relu'))
# model.add(Dense(units=40, activation='relu'))
# model.add(Dense(units=10, activation='relu'))

# LSTM - for better performance
# model.add(LSTM(units=128))

# Bidirectional LSTM
forward_layers = LSTM(units=128, return_sequences=False)
backward_layers = LSTM(units=128, return_sequences=False, go_backwards=True)
model.add(Bidirectional(layer=forward_layers, backward_layer=backward_layers))

# Output Layer
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='adam', loss='mse', metrics=['acc'])

print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 19, 8)             944       
_________________________________________________________________
bidirectional (Bidirectional (None, 256)               140288    
_________________________________________________________________
dense (Dense)                (None, 1)                 257       
Total params: 141,489
Trainable params: 141,489
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(padded_train_ex, train_label, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 3s 3s/step - loss: 0.2500 - acc: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 40ms/step - loss: 0.2496 - acc: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 36ms/step - loss: 0.2490 - acc: 0.9000
Epoch 4/100
1/1 [==============================] - 0s 35ms/step - loss: 0.2484 - acc: 0.6000
Epoch 5/100
1/1 [==============================] - 0s 34ms/step - loss: 0.2476 - acc: 0.8000
Epoch 6/100
1/1 [==============================] - 0s 34ms/step - loss: 0.2466 - acc: 1.0000
Epoch 7/100
1/1 [==============================] - 0s 40ms/step - loss: 0.2453 - acc: 0.9000
Epoch 8/100
1/1 [==============================] - 0s 37ms/step - loss: 0.2437 - acc: 1.0000
Epoch 9/100
1/1 [==============================] - 0s 36ms/step - loss: 0.2416 - acc: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 35ms/step - loss: 0.2389 - acc: 1.0000
Epoch 11/100
1/1 [==============================] - 0s 32ms/step - loss

In [ ]:
# Testing
test_ex = ['দামে বেশি হলেও মানে ভালো, ধন্যবাদ এপেক্স এবং দারাজ কে', 
           'জুতাটি হাতে পেয়ে আমি সত্যিই বিস্মিত', 
           'একদম বাজে, মনে হচ্ছে প্রতারিত হলাম 😡',
           'এতো ফালতু প্রডাক্ট পবো আশা করি নি']

# tokenization and converting words into sequence
dense_test_ex = tokenizer.texts_to_sequences(test_ex)

# padding the test documents
padded_test_ex = pad_sequences(dense_test_ex, maxlen=MAX_LENGTH, padding='post')

prediction = model.predict(padded_test_ex)

print(prediction)

[[0.9956939 ]
 [0.99304175]
 [0.99197876]
 [0.01243237]]
