<a href="https://colab.research.google.com/github/ekramasif/Basic-Machine-Learning/blob/main/Classification/Support_Vector_Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Support Vector Machine (SVM)**

## Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Datasets/Social_Network_Ads.csv')
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

### X & y

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
X

array([[15624510, 'Male', 19, 19000],
       [15810944, 'Male', 35, 20000],
       [15668575, 'Female', 26, 43000],
       ...,
       [15654296, 'Female', 50, 20000],
       [15755018, 'Male', 36, 33000],
       [15594041, 'Female', 49, 36000]], dtype=object)

# Encoding categorical data

## Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
X

array([[0.0, 1.0, 15624510, 19, 19000],
       [0.0, 1.0, 15810944, 35, 20000],
       [1.0, 0.0, 15668575, 26, 43000],
       ...,
       [1.0, 0.0, 15654296, 50, 20000],
       [0.0, 1.0, 15755018, 36, 33000],
       [1.0, 0.0, 15594041, 49, 36000]], dtype=object)

## Encoding the Dependent Variable

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[1.0 0.0 15810075 44 39000]
 [0.0 1.0 15583681 32 120000]
 [1.0 0.0 15733964 38 50000]
 ...
 [0.0 1.0 15591433 36 52000]
 [1.0 0.0 15776348 27 54000]
 [1.0 0.0 15794661 26 118000]]


In [ ]:
print(y_train)

[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [ ]:
print(X_test)

[[0.0 1.0 15725660 30 87000]
 [1.0 0.0 15652400 38 50000]
 [0.0 1.0 15776844 35 75000]
 [1.0 0.0 15738448 30 79000]
 [1.0 0.0 15638003 35 50000]
 [0.0 1.0 15814004 27 20000]
 [1.0 0.0 15610140 31 15000]
 [0.0 1.0 15680587 36 144000]
 [1.0 0.0 15666141 18 68000]
 [0.0 1.0 15622478 47 43000]
 [0.0 1.0 15689425 30 49000]
 [1.0 0.0 15800061 28 55000]
 [0.0 1.0 15773447 37 55000]
 [0.0 1.0 15579212 39 77000]
 [0.0 1.0 15746139 20 86000]
 [1.0 0.0 15789109 32 117000]
 [0.0 1.0 15760570 37 77000]
 [0.0 1.0 15807909 19 85000]
 [1.0 0.0 15654230 55 130000]
 [0.0 1.0 15708228 35 22000]
 [1.0 0.0 15609653 35 47000]
 [1.0 0.0 15746203 47 144000]
 [1.0 0.0 15678168 41 51000]
 [0.0 1.0 15729908 47 105000]
 [1.0 0.0 15614420 23 28000]
 [1.0 0.0 15753861 49 141000]
 [1.0 0.0 15667265 28 87000]
 [0.0 1.0 15697686 29 80000]
 [1.0 0.0 15631070 37 62000]
 [1.0 0.0 15584545 32 86000]
 [0.0 1.0 15587013 21 88000]
 [0.0 1.0 15637593 37 79000]
 [0.0 1.0 15814553 57 60000]
 [0.0 1.0 15622171 37 53000]
 [0.0 1.

In [ ]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 0.98019606 -0.98019606  1.67009484  0.58164944 -0.88670699]
 [-1.02020406  1.02020406 -1.52442817 -0.60673761  1.46173768]
 [ 0.98019606 -0.98019606  0.59613378 -0.01254409 -0.5677824 ]
 ...
 [-1.02020406  1.02020406 -1.4150439  -0.21060859 -0.50979612]
 [ 0.98019606 -0.98019606  1.19419143 -1.10189888 -0.45180983]
 [ 0.98019606 -0.98019606  1.45259625 -1.20093113  1.40375139]]


In [ ]:
print(X_test)

[[-1.02020406e+00  1.02020406e+00  4.78960539e-01 -8.04802115e-01
   5.04963926e-01]
 [ 9.80196059e-01 -9.80196059e-01 -5.54771608e-01 -1.25440855e-02
  -5.67782405e-01]
 [-1.02020406e+00  1.02020406e+00  1.20119022e+00 -3.09640847e-01
   1.57046197e-01]
 [ 9.80196059e-01 -9.80196059e-01  6.59405075e-01 -8.04802115e-01
   2.73018773e-01]
 [ 9.80196059e-01 -9.80196059e-01 -7.57919871e-01 -3.09640847e-01
  -5.67782405e-01]
 [-1.02020406e+00  1.02020406e+00  1.72553483e+00 -1.10189888e+00
  -1.43757673e+00]
 [ 9.80196059e-01 -9.80196059e-01 -1.15107956e+00 -7.05769861e-01
  -1.58254245e+00]
 [-1.02020406e+00  1.02020406e+00 -1.57040131e-01 -2.10608593e-01
   2.15757314e+00]
 [ 9.80196059e-01 -9.80196059e-01 -3.60879806e-01 -1.99318916e+00
  -4.59058115e-02]
 [-1.02020406e+00  1.02020406e+00 -9.76984730e-01  8.78746198e-01
  -7.70734413e-01]
 [-1.02020406e+00  1.02020406e+00 -3.23319037e-02 -8.04802115e-01
  -5.96775549e-01]
 [ 9.80196059e-01 -9.80196059e-01  1.52879272e+00 -1.00286662e+00

## Training the SVM model on the Training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Predicting a new result

In [ ]:
print(classifier.predict(sc.transform([[1.0, 0.0, 1574661, 76, 11800]])))

[1]


## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[64  4]
 [ 8 24]]


0.88

## Visualising the Training set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('SVM (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

## Visualising the Test set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('SVM (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()